# print("hello\ankith")
# print("hello\bharat")
# print("hello\chandu")
# print("hello\dhurgabhavani")
# print("hello\eswear")
# print("hello\garuk")
# print("hello\haruk")
# print("hello\iaruk")
# print("hello\jaruk")
# print("hello\karuk")
# print("hello\laruk")
# print("hello\maruk")
# print("hello\naruk")
# print("hello\oaruk")
# print("hello\paruk")
# print("hello\qaruk")
# print("hello\raviteja")
# print("hello\shiva")
# print("hello\telugu ")
# print("hello\usman")
# print("hello\venkey")
# print("hello\worldwide")
# print("hello\xerox")
print("hello\yerramnaidu")
print("hello\zoom")